# Render Blueprint file
services:
  # Web Crawler background worker service
  - type: cron
    name: web-crawler
    plan: starter
    env: docker
    dockerfilePath: ./Dockerfile.render  # Use our custom Dockerfile for Render
    # No need for build/start commands - Docker handles this
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: USE_BROWSER
        value: "true"
      - key: OPENAI_API_KEY
        sync: false
      - key: START_URLS
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
    disk:
      name: crawler-data
      mountPath: /var/data
      sizeGB: 5
    autoDeploy: false  # Set to true for automatic deploys on push 