# Render Blueprint file
services:
  # Web Crawler background worker service
  - type: cron
    name: web-crawler
    plan: starter
    env: node # Using Node instead of Docker
    buildCommand: |
      # Install dependencies
      pip install -r requirements.txt
      pip install -e .
      
      # Install Playwright with only Chromium
      pip install playwright
      
      # Set Playwright browsers path to Render-specific directory
      export PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/playwright
      python -m playwright install chromium
    startCommand: python orchestrator.py
    schedule: "0 9 */2 * *"  # Run at 9 AM UTC every 2 days
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: USE_BROWSER
        value: "true"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/opt/render/project/playwright"
      # Secret environment variables - set in Render dashboard
      - key: OPENAI_API_KEY
        sync: false
      - key: START_URLS
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
    autoDeploy: true