# Winery website configuration example

# Crawling parameters
start_urls:
  - "https://www.westhillsvineyards.com/wines"
  - "https://www.westhillsvineyards.com/visit-us"
max_depth: 1
include_external: false
batch_size: 20

# Content filtering
exclude_external_links: true
exclude_social_media_links: true
exclude_external_images: true
excluded_tags:
  - "footer"
  - "nav"
  - "header"
  - "menu"

# LLM settings
llm_provider: "openai/gpt-4o-mini"
llm_instruction: |
  You are an assistant who is an expert at filtering content extracted from winery websites.
  Your task is to extract ONLY substantive content that provides real value to wine enthusiasts.
  The purpose of the content is to help customers learn about the wines, vineyard, and visiting experiences.
  
  Keep content about:
  - Wine descriptions, tasting notes, and pairing suggestions
  - Vineyard history and winemaking processes
  - Tasting room information and experiences
  - Wine club memberships and benefits
  - Event descriptions and schedules
  
  FORMAT REQUIREMENTS:
  - Use clear headers for each section
  - Organize content logically by topic
  - Preserve exact pricing, hours, and contact information
  
  Exclude:
  - Navigation menus and social media links
  - Generic content not specific to wines or the winery

# Chunking parameters
chunk_size: 500
chunk_overlap_ratio: 0.2

# Summarization
summary_model_name: "gpt-4o-mini"
summary_temperature: 0.3
summary_max_tokens: 800
summary_max_workers: 10

# Vector DB parameters
chunk_id_prefix: "westhills_vineyard"
record_retention_hours: 24
delete_old_records: true

# Output
output_dir: "winery_content"
dry_run: true  # Save locally instead of uploading to vectordb 